language: python
python: "3.6"

install :
  - pip install pylama
  - pip install pytest
  - pip install coverage
  - pip install coveralls
  - pip install PyQt5
  - pip install PySide
  - pip install matplotlib


script :
  - pylama
  - coverage run --source ./ -m pytest -v
  - coverage report

after_success:
  - coveralls
