language: python
python: "2.7"

install :
  - pip install pylama
  - pip install pytest
  - pip install coverage
  - pip install coveralls
  - pip install codacy-coverage

script :
  - pylama
  - coverage run --source ./ -m pytest -v
  - coverage report

after_success:
  - coveralls
